name: blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: update blog.ronething.cn posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.ronething.cn/atom.xml"
          template: $newline - [$title]($url) - $date
          date_format: "isoUtcDateTime"
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/12897479" 
