name: Waka Readme

on:
  schedule:
    # 0:30 UTC -> 8:30 UTC+8
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: cloud-org/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: False
          SHOW_LINES_OF_CODE: False
          SHOW_LOC_CHART: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
